### ISSUE TITLE
Evaluation code

### ISSUE THREAD

**Issue by Haochen-Wang409** [minhoooo1/CatMAE#1]
Hi @minhoooo1, excellent work on self-supervised video pre-training! It is really interesting that such a simple paradigm contributes to superior performances!

Since this repo only contains the pre-training code, I wonder if you have any plans to release the evaluation code on DAVIS-2017 and K-400?

**Comment by minhoooo1** [comment]
Thank you for your interest. I plan to update the code, paper, and weights this week.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月8日(星期三) 上午10:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: [minhoooo1/CatMAE] Evaluation code (Issue #1)





 
Hi @minhoooo1, excellent work on self-supervised video pre-training! It is really interesting that such a simple paradigm contributes to superior performances!
 
Since this repo only contains the pre-training code, I wonder if you have any plans to release the evaluation code on DAVIS-2017 and K-400?

**Comment by Haochen-Wang409** [comment]
Thank you very much for the prompt reply :)

**Comment by minhoooo1** [comment]
@Haochen-Wang409 Can you provide your email address? I would like to send you the assessment code, as all the content cannot be made public on GitHub at the moment.

**Comment by Haochen-Wang409** [comment]
Thank you very much!! My e-mail is 1137810041@qq.com

**Comment by rvandeghen** [comment]
Hello @minhoooo1 

Is it possible to send your codes to my email address ?
I am also interested in your work.
It is r.vandeghen@uliege.be

Regards

**Comment by minhoooo1** [comment]
@rvandeghen

**Comment by huiwon-jang** [comment]
Hello @minhoooo1!

I enjoyed your work! Thank you for your great contribution to visual self-supervised learning fields :)

Is it possible to send your evaluation code to my e-mail too?: huiwoen0516@kaist.ac.kr

Best,
